### ISSUE TITLE
Consider moving the repo to `tree-sitter-grammars`

### ISSUE THREAD

**Issue by amaanq** [elm-tooling/tree-sitter-elm#146]
Hey @razzeee, I hope you've been well. We at nvim-treesitter (and potentially more folks from other teams interested in an ecosystem-wide effort to maintain grammars) have decided to move all of our own grammars collectively into one org, to make it easier for us all to fix bugs or keep things up to date (scanner crashes, regenerating with the latest abi, etc.)  without having to rely on one sole maintainer (you).

This is 100% optional, and please don't feel pressured or feel like you have an obligation of moving the grammar to the org, but it will help everyone a lot, us at nvim-treesitter, other users downstream, to know that a grammar won't ever die should a maintainer call it quits or go MIA. We also have org-wide actions that we maintain (out of sight, out of mind for you) and a grammar template (soon for newbies) in place to ensure authors have a better experience with working on and fixing tree-sitter grammars. It also enables anyone looking to find grammars for a specific language to only have to search in one spot

Our org is here: https://github.com/tree-sitter-grammars

If you want to participate (and don't worry, you'll still have full write perms to your repo, just no admin access), that'd be great! All you have to do is transfer the repo to me in the repository settings and I'll handle it from there. Thanks a lot, and again no worries if the answer is no!

**Comment by razzeee** [comment]
I guess that might break the pages deployment and publishing to npm/cargo (or leak the current tokens to you?)

**Comment by amaanq** [comment]
Hm it might, but does that just use links to the current grammar (i.e. https://github.com/elm-tooling/tree-sitter-elm ?) If so, those would just get redirected. Also, tokens can't be leaked but I understand the apprehension (no seriously, go to your secrets and try viewing any tokens, you **can't**, you can only *change* them once they're set).

What you can do is restrict the scope of your crates/npm token to be granular and only have write perms to tree-sitter-elm if you are concerned (I do this with all of my tokens)

**Comment by amaanq** [comment]
Yeah true I didn't think about that, and yes it is just core members of neovim/nvim-treesitter.
