### ISSUE TITLE
Get rid of todo's in code

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/tree-sitter-elm#79]

**Comment by nlok5923** [comment]
@Razzeee I want to work on this issue please can you assign me this also as I am new to this project I will need you help to resolve this issue.
 So can you please elaborate the issue a bit.

**Comment by Razzeee** [comment]
I think this is the only tado left https://github.com/elm-tooling/tree-sitter-elm/blob/master/grammar.js#L420

Unfortunately, I don't think it's solvable. We would need help from upstream or just give up and remove the to do.

https://github.com/tree-sitter/tree-sitter/issues/931

**Comment by nlok5923** [comment]
@Razzeee  no problem sir but if possible please can you let me know some good first issue as i am really interested in this project also new to it and like to contribute in it,

**Comment by Razzeee** [comment]
I think this project is in a good place right now, there's not much to do that adds value.

https://github.com/elm-tooling/tree-sitter-elm/issues/78 might be the only thing, but I don't think thats an easy thing to start on
